# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ fabric_1_16 ]
  pull_request:
    branches: [ fabric_1_16 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.1.1

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: Gradle Build
      uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: current
        arguments: build
