name: Publish on Modrinth and Curseforge

on:
  release:
    types: [published]

jobs:
  Publish:
    runs-on: ubuntu-latest
    name: Publish Minecraft Mods

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 18

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: build

      - uses: Kir-Antipov/mc-publish@v2.1
        with:
          modrinth-id: oGU9LXKC
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 369343
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}
