name: Publish on Modrinth and Curseforge

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish Minecraft Mods
    environment: publish

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 25

      - name: Gradle Setup
        uses: gradle/actions/setup-gradle@v6

      - run: ./gradlew build

      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          name: ""
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
